apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mosaicstorage
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: mosaiclocaldev
  - name: storageAccessKey
    secretKeyRef:
      name: mosaicStorageKey
      value: mosaicStorageKey
  - name: container
    value: mosaics
  #- name: decodeBase64
  #  value: true
auth:
  secretStore: local-secret-store