apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: tilestorage
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: mosaiclocaldev
  - name: storageAccessKey
    secretKeyRef:
      name: tileStorageKey
      value: tileStorageKey
  - name: container
    value: tiles
  - name: decodeBase64
    value: true
auth:
  secretStore: local-secret-store