version: '3.4'

services:
  zipkin:
    image: openzipkin/zipkin-slim
    networks:
      - mosaicnet

  redis:
    image: "redis:alpine"
    networks:
      - mosaicnet

  mosaic.tilesapi:
    image: ${DOCKER_REGISTRY-}mosaictilesapi
    build:
      context: .
      dockerfile: Mosaic.TilesApi/Dockerfile
    networks:
      - mosaicnet

  mosaic.tilesapi.dapr:
    image: "daprio/daprd:1.5.1"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "tilesapi",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.tilesapi"

  mosaic.mosaicapi:
    image: ${DOCKER_REGISTRY-}mosaicmosaicapi
    build:
      context: .
      dockerfile: Mosaic.MosaicApi/Dockerfile
    networks:
      - mosaicnet

  mosaic.mosaicapi.dapr:
    image: "daprio/daprd:1.5.1"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "mosaicapi",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.mosaicapi"

  mosaic.tileprocessor:
    image: ${DOCKER_REGISTRY-}mosaictileprocessor
    build:
      context: .
      dockerfile: Mosaic.TileProcessor/Dockerfile
    networks:
      - mosaicnet

  mosaic.tileprocessor.dapr:
    image: "daprio/daprd:1.5.1"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "tileprocessor",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
       "-log-level", "debug"
     ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.tileprocessor"

  mosaic.frontend:
    image: ${DOCKER_REGISTRY-}mosaicfrontend
    build:
      context: .
      dockerfile: Mosaic.FrontEnd/Dockerfile
    networks:
      - mosaicnet

  mosaic.frontend.dapr:
    image: "daprio/daprd:1.5.1"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "frontend",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.frontend"
  
  mosaic.mosaicgenerator:
    image: ${DOCKER_REGISTRY-}mosaicmosaicgenerator
    build:
      context: .
      dockerfile: Mosaic.MosaicGenerator/Dockerfile
    networks:
      - mosaicnet

  mosaic.mosaicgenerator.dapr:
    image: "daprio/daprd:1.5.1"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "tileprocessor",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
       "-log-level", "debug"
     ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.mosaicgenerator"

# only needed if using actors
  
  dapr-placement:
    image: "daprio/dapr:1.6.0"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    networks:
      - mosaicnet

networks:
  mosaicnet:
    
  volumes:
      