version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}mosaicapigateway
    build:
      context: .
      dockerfile: envoy/Dockerfile
    ports:
      - "9901:9901"
      - "10000:10000"
    networks:
      - mosaicnet

  apigateway.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - apigateway
    command: ["./daprd",
      "-app-id", "apigateway",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:apigateway"

  zipkin:
    image: openzipkin/zipkin-slim
    networks:
      - mosaicnet

  redis:
    image: redis:alpine
    networks:
      - mosaicnet

  mosaic.frontend.server:
    image: ${DOCKER_REGISTRY-}mosaicfrontendserver
    build:
      context: .
      dockerfile: Mosaic.FrontEnd.Server/Dockerfile
    networks:
      - mosaicnet

  mosaic.frontend.server.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "frontend",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.frontend.server"

  mosaic.tilesapi.db:
    image: postgis/postgis
    networks:
      - mosaicnet

  mosaic.tilesapi:
    image: ${DOCKER_REGISTRY-}mosaictilesapi
    build:
      context: .
      dockerfile: Mosaic.TilesApi/Dockerfile
    networks:
      - mosaicnet
    depends_on:
      - mosaic.tilesapi.db

  mosaic.tilesapi.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "tilesapi",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.tilesapi"

  mosaic.mosaicapi:
    image: ${DOCKER_REGISTRY-}mosaicmosaicapi
    build:
      context: .
      dockerfile: Mosaic.MosaicApi/Dockerfile
    networks:
      - mosaicnet

  mosaic.mosaicapi.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "mosaicapi",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
      "-log-level", "debug"
      ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.mosaicapi"

  mosaic.tileprocessor:
    image: ${DOCKER_REGISTRY-}mosaictileprocessor
    build:
      context: .
      dockerfile: Mosaic.TileProcessor/Dockerfile
    networks:
      - mosaicnet

  mosaic.tileprocessor.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "tileprocessor",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
       "-log-level", "debug"
     ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.tileprocessor"

  mosaic.mosaicgenerator:
    image: ${DOCKER_REGISTRY-}mosaicmosaicgenerator
    build:
      context: .
      dockerfile: Mosaic.MosaicGenerator/Dockerfile
    networks:
      - mosaicnet

  mosaic.mosaicgenerator.dapr:
    image: "daprio/daprd:1.9.5"
    depends_on:
      - dapr-placement
    command: ["./daprd",
      "-app-id", "mosaicgenerator",
      "-app-port", "80",
      "-placement-host-address", "dapr-placement:50000",
      "-components-path", "/components",
      "-config", "/components/config.yaml",
       "-log-level", "debug"
     ]
    volumes:
      - "./components/:/components"
    network_mode: "service:mosaic.mosaicgenerator"

# only needed if using actors
  
  dapr-placement:
    image: "daprio/dapr:1.9.5"
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    networks:
      - mosaicnet

networks:
  mosaicnet:
    
  volumes:
      
