name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_SERVER }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_SERVER }}/mosaic/frontend:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/frontend:latest -f ./src/Mosaic.FrontEnd/Dockerfile ./src 

    - name: Push the Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/frontend -a
