name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: src
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    #- uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build ./src --file ./src/Mosaic.FrontEnd/Dockerfile --tag mosaicfrontend:$(date +%s)

    - name: Docker Login
      uses: docker/login-action@v1.13.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.DOCKER_SERVER }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}

    
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0
      with:
        context: src
        # Path to the Dockerfile
        file: ./Mosaic.FrontEnd/Dockerfile
        # List of tags
        tags: mosaicfrontend:${{github.sha}},mosaicfrontend:latest
