name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
    - src/**
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_SERVER }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

# tiles api
    - name: Build the TilesApi Docker image
      run: docker build --build-arg COMMIT_ID=${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/tilesapi:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/tilesapi:latest -f ./src/Mosaic.TilesApi/Dockerfile ./src 

    - name: Push the TilesApi Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/tilesapi -a

# mosiac api
    - name: Build the Mosaic Api Docker image
      run: docker build -t ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicapi:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicapi:latest -f ./src/Mosaic.MosaicApi/Dockerfile ./src 

    - name: Push the MosaicApi Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicapi -a

# mosaic generator

    - name: Build the Mosaic Generator Docker image
      run: docker build -t ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicgenerator:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicgenerator:latest -f ./src/Mosaic.MosaicGenerator/Dockerfile ./src 

    - name: Push the MosaicApi Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/mosaicgenerator -a

# tile processor
    - name: Build the TileProcessor Docker image
      run: docker build -t ${{ secrets.DOCKER_SERVER }}/mosaic/tileprocessor:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/tileprocessor:latest -f ./src/Mosaic.TileProcessor/Dockerfile ./src 

    - name: Push the TileProcessor Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/tileprocessor -a
