name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths: 
    - src/Mosaic.Tiles.Actors/**
    - src/Mosaic.Tiles.Actors.Interfaces/**
   
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Docker Login
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_SERVER }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

# tile actors
    - name: Build the TilesActors Docker image
      run: docker build -t ${{ secrets.DOCKER_SERVER }}/mosaic/tilesactors:${{github.sha}} -t ${{ secrets.DOCKER_SERVER }}/mosaic/tilesactors:latest -f ./src/Mosaic.Tiles.Actors/Dockerfile ./src 

    - name: Push the TilesActors Docker image to the registry
      run: docker push  ${{ secrets.DOCKER_SERVER }}/mosaic/tilesactors -a
